apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: auth-config
deploy:
  helm:
    releases:
      - name: auth-config
        chartPath: istio/istio-auth-module
        namespace: istio-system
      
        