# https://istio.io/latest/docs/ops/integrations/prometheus/
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: prometheus
# requires:
#   - configs: [istiod]
deploy:
  helm:
    releases:
      - name: prometheus
        remoteChart: prometheus
        repo: https://prometheus-community.github.io/helm-charts
        namespace: prometheus
        createNamespace: true
        valuesFiles:
          - istio/istio-system/values/prometheus-values.yaml
---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: kiali-operator
requires:
  - configs: [prometheus]
deploy:
  helm:
    releases:
      - name: kiali-operator
        remoteChart: kiali-operator
        repo: https://kiali.org/helm-charts
        namespace: kiali-operator
        createNamespace: true
---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: kiali
requires:
  - configs: [kiali-operator]
manifests:
  rawYaml:
    - istio/istio-system/manifests/kiali-dashboard.yaml
deploy:
  kubectl: 
    flags:
      delete: 
        - "--wait=true"
